### ISSUE TITLE
UTF-8 errors on full run

### ISSUE THREAD

**Issue by ghost** [open-contracting/extensions-data-collector#6]

**Comment by odscjames** [comment]
This error was reported by @kindly 

I don't get this error. Hmmmmm.

**Comment by ghost** [comment]
Replicated:

```
https://api.github.com/repos/open-contracting/public-private-partnerships/zipball/v1.1
open-contracting-public-private-partnerships-a18499c/docs/_assets/disclosure-framework.png


Traceback (most recent call last):
  File "cli.py", line 19, in <module>
    main()
  File "cli.py", line 15, in main
    runner.run()
  File "/vagrant/open-contracting-extensions-data-collector/ocdsextensionsdatacollector/runner.py", line 62, in run
    outfile.write(version_zipfile.read(name).decode('utf-8'))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte
```
